spring:
  datasource:
    url: jdbc:mysql://<RDS_ENDPOINT>:3306/prod_db?useSSL=false&serverTimezone=UTC
    username: prod_user
    password: prod_pass
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
